# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M-OXFkE6drfr46JonFT7M8IIOoXPo1Bg
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

# 1. Cargar TU dataset de YouTube
# Usamos el nombre exacto del archivo que subiste
nombre_archivo = 'Youtube_Unificado_Procesado (4).csv'
df = pd.read_csv(nombre_archivo)

# Limpiamos un poco por si hay filas vacías en el texto o la clase
df = df.dropna(subset=['CONTENT', 'CLASS'])

# 2. Dividir los datos: 70% para entrenar y 30% para probar
X_train, X_test, y_train, y_test = train_test_split(
    df['CONTENT'],
    df['CLASS'],
    test_size=0.3,
    random_state=42
)

# 3. Preprocesamiento: Vectorización de texto (TF-IDF)
vectorizador = TfidfVectorizer(stop_words='english')
X_train_vectorizado = vectorizador.fit_transform(X_train)
X_test_vectorizado = vectorizador.transform(X_test)

# 4. Crear la Red Neuronal (Perceptrón Multicapa)
# 2 capas ocultas con 8 neuronas cada una, como en los ejemplos clásicos
red_neuronal = MLPClassifier(hidden_layer_sizes=(8, 8), max_iter=500, random_state=42)

# 5. Entrenar el modelo con tus datos de YouTube
print("Entrenando la red neuronal con comentarios de YouTube...")
red_neuronal.fit(X_train_vectorizado, y_train)

# 6. Realizar predicciones
predicciones = red_neuronal.predict(X_test_vectorizado)

# 7. Evaluar el modelo
precision = accuracy_score(y_test, predicciones)
print(f"\n¡Entrenamiento completado! Precisión del modelo: {precision * 100:.2f}%\n")

print("Reporte de Clasificación (0 = No Spam, 1 = Spam):")
print(classification_report(y_test, predicciones))

# --- Prueba tu propia red neuronal con nuevos comentarios ---
def predecir_spam(mensaje):
    mensaje_vectorizado = vectorizador.transform([mensaje])
    prediccion = red_neuronal.predict(mensaje_vectorizado)[0]
    resultado = "SPAM 🚨" if prediccion == 1 else "NO ES SPAM ✅"
    return resultado

print("\n--- PRUEBAS EN VIVO ---")
comentario_1 = "Check out my new channel, please subscribe!!!"
comentario_2 = "This video is so helpful, thank you for making it."

print(f"Comentario: '{comentario_1}' -> Predicción: {predecir_spam(comentario_1)}")
print(f"Comentario: '{comentario_2}' -> Predicción: {predecir_spam(comentario_2)}")


